name: potemkin
channels:
  - defaults
dependencies:
  - aws-c-common==0.8.5
  - blas==1.0
  - bzip2==1.0.8
  - c-ares==1.19.1
  - ca-certificates==2025.2.25
  - jpeg==9e
  - libbrotlicommon==1.0.9
  - libcxx==14.0.6
  - libdeflate==1.17
  - libev==4.33
  - libffi==3.4.4
  - libiconv==1.16
  - libsodium==1.0.18
  - libwebp-base==1.3.2
  - llvm-openmp==14.0.6
  - ncurses==6.4
  - pandoc==3.4
  - pybind11-abi==5
  - tzdata==2024a
  - utf8proc==2.6.1
  - xxhash==0.8.0
  - xz==5.4.6
  - yaml==0.2.5
  - zlib==1.2.13
  - aws-c-cal==0.5.20
  - aws-c-compression==0.2.16
  - aws-c-sdkutils==0.1.6
  - aws-checksums==0.1.13
  - expat==2.6.3
  - gflags==2.2.2
  - icu==73.1
  - lerc==3.0
  - libabseil==20240116.2
  - libbrotlidec==1.0.9
  - libbrotlienc==1.0.9
  - libedit==3.1.20230828
  - libgfortran5==11.3.0
  - libllvm14==14.0.6
  - libpng==1.6.39
  - lz4-c==1.9.4
  - openssl==3.0.16
  - pcre2==10.42
  - re2==2022.04.01
  - readline==8.2
  - snappy==1.2.1
  - tk==8.6.14
  - zeromq==4.3.5
  - aws-c-io==0.13.10
  - freetype==2.12.1
  - glog==0.5.0
  - krb5==1.20.1
  - libclang13==14.0.6
  - libevent==2.1.12
  - libgfortran==5.0.0
  - libnghttp2==1.57.0
  - libprotobuf==4.25.3
  - libssh2==1.11.0
  - libxml2==2.13.1
  - sqlite==3.45.3
  - zstd==1.5.5
  - aws-c-event-stream==0.2.15
  - aws-c-http==0.6.25
  - cyrus-sasl==2.1.28
  - gettext==0.21.0
  - libboost==1.82.0
  - libclang==14.0.6
  - libcurl==8.9.1
  - libgrpc==1.62.2
  - libopenblas==0.3.21
  - libpq==12.17
  - libtiff==4.5.1
  - libxslt==1.1.41
  - orc==2.0.1
  - python==3.12.5
  - aiohappyeyeballs==2.4.0
  - annotated-types==0.6.0
  - appnope==0.1.3
  - async-lru==2.0.4
  - attrs==23.1.0
  - aws-c-auth==0.6.19
  - aws-c-mqtt==0.7.13
  - boost-cpp==1.82.0
  - brotli-python==1.0.9
  - certifi==2025.4.26
  - charset-normalizer==3.3.2
  - debugpy==1.6.7
  - decorator==5.1.1
  - defusedxml==0.7.1
  - dill==0.3.8
  - distro==1.9.0
  - entrypoints==0.4
  - et_xmlfile==1.1.0
  - executing==0.8.3
  - filelock==3.13.1
  - frozenlist==1.4.0
  - fsspec==2024.6.1
  - h11==0.14.0
  - idna==3.7
  - ipython_genutils==0.2.0
  - jiter==0.6.1
  - joblib==1.4.2
  - json5==0.9.6
  - jupyterlab_widgets==3.0.10
  - lcms2==2.12
  - libglib==2.78.4
  - lxml==5.2.1
  - markupsafe==2.1.3
  - mistune==2.0.4
  - mpmath==1.3.0
  - multidict==6.0.4
  - mysql==5.7.24
  - nest-asyncio==1.6.0
  - networkx==3.3
  - numpy-base==1.26.4
  - openjpeg==2.5.2
  - overrides==7.4.0
  - packaging==24.1
  - pandocfilters==1.5.0
  - parso==0.8.3
  - platformdirs==3.10.0
  - ply==3.11
  - prometheus_client==0.14.1
  - psutil==5.9.0
  - ptyprocess==0.7.0
  - pure_eval==0.2.2
  - pycparser==2.21
  - pygments==2.15.1
  - pyqt5-sip==12.13.0
  - pysocks==1.7.1
  - python-fastjsonschema==2.16.2
  - python-json-logger==2.0.7
  - python-tzdata==2023.3
  - python-xxhash==2.0.2
  - pytz==2024.1
  - pyyaml==6.0.1
  - pyzmq==25.1.2
  - regex==2024.9.11
  - rfc3986-validator==0.1.1
  - rpds-py==0.10.6
  - safetensors==0.4.4
  - send2trash==1.8.2
  - setuptools==75.1.0
  - six==1.16.0
  - sniffio==1.3.0
  - soupsieve==2.5
  - threadpoolctl==3.5.0
  - tornado==6.4.1
  - tqdm==4.66.5
  - traitlets==5.14.3
  - typing_extensions==4.11.0
  - wcwidth==0.2.5
  - webencodings==0.5.1
  - websocket-client==1.8.0
  - wheel==0.44.0
  - widgetsnbextension==4.0.10
  - aiosignal==1.2.0
  - anyio==4.2.0
  - asttokens==2.0.5
  - aws-c-s3==0.1.51
  - babel==2.11.0
  - beautifulsoup4==4.12.3
  - bleach==4.1.0
  - cffi==1.17.1
  - comm==0.2.1
  - glib-tools==2.78.4
  - httpcore==1.0.2
  - jedi==0.19.1
  - jinja2==3.1.4
  - jupyter_core==5.7.2
  - jupyterlab_pygments==0.1.2
  - libthrift==0.15.0
  - matplotlib-inline==0.1.6
  - multiprocess==0.70.15
  - numpy==1.26.4
  - openpyxl==3.1.5
  - pexpect==4.8.0
  - pillow==10.4.0
  - pip==24.2
  - prompt-toolkit==3.0.43
  - python-dateutil==2.9.0post0
  - qtpy==2.4.1
  - referencing==0.30.2
  - rfc3339-validator==0.1.4
  - sip==6.7.12
  - sympy==1.13.2
  - terminado==0.17.1
  - tinycss2==1.2.1
  - typing-extensions==4.11.0
  - urllib3==2.2.2
  - yarl==1.11.0
  - aiohttp==3.10.5
  - argon2-cffi-bindings==21.2.0
  - aws-crt-cpp==0.18.16
  - bottleneck==1.3.7
  - glib==2.78.4
  - httpx==0.27.0
  - jsonschema-specifications==2023.7.1
  - jupyter_client==7.4.9
  - jupyter_server_terminals==0.4.4
  - numexpr==2.8.7
  - prompt_toolkit==3.0.43
  - pydantic-core==2.20.1
  - pytorch==2.3.0
  - requests==2.32.3
  - scipy==1.13.1
  - stack_data==0.2.0
  - argon2-cffi==21.3.0
  - aws-sdk-cpp==1.10.55
  - gstreamer==1.14.1
  - huggingface_hub==0.24.6
  - ipython==8.27.0
  - jsonschema==4.19.2
  - pandas==2.2.3
  - pydantic==2.8.2
  - scikit-learn==1.5.1
  - torchvision==0.18.1
  - accelerate==0.34.2
  - arrow-cpp==16.1.0
  - gst-plugins-base==1.14.1
  - ipykernel==6.28.0
  - ipywidgets==8.1.2
  - jupyter_events==0.10.0
  - nbformat==5.9.2
  - openai==1.52.1
  - tokenizers==0.19.1
  - jupyter_console==6.6.3
  - nbclient==0.8.0
  - pyarrow==16.1.0
  - qt-main==5.15.2
  - datasets==3.0.0
  - nbconvert-core==7.16.4
  - pyqt==5.15.10
  - nbconvert-pandoc==7.16.4
  - qtconsole==5.6.0
  - transformers==4.44.2
  - nbconvert==7.16.4
  - jupyter_server==2.14.1
  - jupyter-lsp==2.2.0
  - jupyterlab_server==2.27.3
  - notebook-shim==0.2.3
  - jupyterlab==4.2.5
  - nbclassic==1.1.0
  - notebook==6.5.7
  - jupyter==1.0.0
  - jupyter_contrib_core==0.4.0
  - jupyter_highlight_selected_word==0.2.0
  - jupyter_latex_envs==1.4.6
  - jupyter_nbextensions_configurator==0.6.1
  - jupyter_contrib_nbextensions==0.7.0
  - pip:
    - transformer_lens